#!/bin/bash
set -euo pipefail
build_version=${build_version:-$(git rev-parse HEAD)}
TARGET=${1:-generated/}
rm -rf "$TARGET"
mkdir -p "$TARGET"
jsonnet -J vendor/ -J lib/ \
  --ext-str build_version="$build_version" \
  site.jsonnet \
  -S \
  --create-output-dirs \
  --multi "$TARGET"
