version: 2.1
executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install jsonnet + jb
          command: |
            curl -Lsfo jsonnet.deb https://github.com/google/go-jsonnet/releases/download/v0.17.0/jsonnet-go_0.17.0_linux_amd64.deb
            sudo dpkg -i jsonnet.deb

            curl -Lsf https://github.com/jsonnet-bundler/jsonnet-bundler/releases/download/v0.4.0/jb-linux-amd64 \
              | install -m755 /dev/stdin /tmp/jb
            /tmp/jb install
      - run:
          name: Run tests
          command: ./test
      - run:
          name: Build Docker images
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            ./generate
            cd generated/
            for s in ./*/image-build.sh; do bash "$s"; done
            for s in ./*/image-push.sh; do bash "$s"; done
      - store_artifacts:
          path: generated/
workflows:
  version: 2
  build:
    jobs:
      - build: {}
